<a href="https://colab.research.google.com/github/samalasathwika/Libraries/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
review = pd.read_csv("/content/anime.csv")

In [ ]:
#no.of rows, columns
review.shape

In [ ]:
#using head
review.head()

In [ ]:
#using tail
review.tail()

In [ ]:
#display whole dataser
review

In [ ]:
#display specific column
review.name

In [ ]:
#set no.of rows to display
pd.set_option('display.max_rows',4)

In [ ]:
review.head()

In [ ]:
#display 1th name of the dataset
review.name[0]

In [ ]:
#index based selection
review.iloc[0]

In [ ]:
#all rows using iloc
review.iloc[:,0]

In [ ]:
#specified no.of rows
review.iloc[:3,1]

In [ ]:
review.iloc[1:3,1]

In [ ]:
#retrieving from the end using iloc
review.iloc[-6,:]

In [ ]:
#manipulating the index
review.set_index("name")

In [ ]:
#check if there are any other values as my input
review.name=='Kimi no Na wa.'

In [ ]:
#creating new row
review['new']="hi"
review['new']

In [ ]:
#new row with reverse indexing
review['index_backward']=range(len(review),0,-1)
review['index_backward']

In [ ]:
#summary function(describe)
review.rating.describe()

In [ ]:
#describe on str
review.name.describe()

In [ ]:
#finding the unq
review.name.unique()

In [ ]:
#finding how much better the ratings are compared to the average
review_rating_mean=review.rating.mean()
review.rating.map(lambda p : p - review_rating_mean)

In [52]:
#using apply()
def remean_row(row):
  row.rating=row.rating-review_rating_mean
  return row
review.apply(remean_row,axis='columns')

,anime_id,name,genre,type,episodes,rating,members,new,index_backward
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,2.896098,200630,hi,12294
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,2.786098,793665,hi,12293
...,...,...,...,...,...,...,...,...,...
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,-1.493902,175,hi,2
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,-1.013902,142,hi,1

In [ ]:
review.name+" - "+review.genre

In [51]:
#using groupby
review.groupby('rating').rating.count()

rating
1.67     1
1.92     1
        ..
9.60     1
10.00    1
Name: rating, Length: 598, dtype: int64

In [53]:
#min
review.groupby('rating').episodes.min()

rating
1.67           1
1.92           1
          ...
9.60     Unknown
10.00          1
Name: episodes, Length: 598, dtype: object

In [59]:
review.groupby('rating').apply(lambda df : df.episodes.iloc[0])

/tmp/ipykernel_713/3755637608.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  review.groupby('rating').apply(lambda df : df.episodes.iloc[0])

rating
1.67           1
1.92           1
          ...
9.60     Unknown
10.00          1
Length: 598, dtype: object